### PR TITLE
Switch to use Popen instead of run

### PR DESCRIPTION
**Pull request by rjschwei**
+ The run() fuction in the subprocess module was implemented after
    Python 3.4. However, we need to support Python 3.4 for SLES 12

### CODE REVIEW

**Comment by rjschwei** [comment]
Need some help with the exception path testing. Feel free to commit to the branch as you see fit. Thanks

**Comment by schaefi** [comment]
I'll take a look...

**Comment by schaefi** [comment]
forgot what I said, you are right, I'm using subprocess.Popen in kiwi too, but my class provides a run method. Was confused for a moment ;)

**Comment by rjschwei** [comment]
@schaefi thanks for the help with the tests :)

**Pull request merged**
